In [17]:
import numpy as np

tensor= np.array ([
    [[[1,2],[3,4],[5,6]]],
    [[[1,2],[3,4],[5,6]]],
    [[[1,2],[3,4],[5,6]]]
])
tensor 

array([[[[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]]]])

In [21]:

arreglo=np.random.randint(1,10, size=(2,2))
arreglo

array([[3, 4],
       [9, 9]])

In [23]:
arreglo1=np.random.rand(2,3)
arreglo1

array([[0.94729678, 0.38632722, 0.99428174],
       [0.5512755 , 0.3440978 , 0.05708537]])

In [41]:
arreglo=np.random.randint(1,10, size =(2,20))
arreglo 

array([[9, 1, 2, 3, 8, 4, 5, 7, 3, 1, 7, 3, 9, 8, 4, 2, 4, 3, 1, 3],
       [7, 5, 9, 5, 2, 1, 8, 3, 9, 4, 4, 4, 3, 5, 4, 5, 4, 4, 4, 5]])

In [81]:
import numpy as np
import random
vec1 = np.random.randint(1,100, size =(1,20))
vec2 = vec1.reshape(4, 5)
vec2
vec1
                         

array([[ 1, 28, 50, 60, 51, 99, 56, 54, 60, 14, 89, 46, 37, 71, 99, 57,
         3, 82, 39,  7]])

In [61]:
vec1 = np.random.randint(1,100, size =(1, random.randint(5,15)))
f = int(input("ingrese cantidad de filas: "))
c = int (input("ingrese cantidad de columnas: "))
arreglo = np.any(vec1)
nuevo=arreglo.reshape(f,c)
nuevo

vec1
        

ingrese cantidad de filas:  


ValueError: invalid literal for int() with base 10: ''

In [117]:
matrix=np.random.randint(1,100,size=(5,5))
matrix

array([[39,  4, 12, 72, 96],
       [ 2, 26, 53, 65, 61],
       [ 6, 57, 82, 82, 41],
       [25, 38, 73, 23, 40],
       [57, 92, 41,  1, 84]])

In [119]:
mitad= matrix[:,2:]
mitad

array([[12, 72, 96],
       [53, 65, 61],
       [82, 82, 41],
       [73, 23, 40],
       [41,  1, 84]])

In [121]:
suma= np.sum(mitad)
suma

826

In [123]:
promedio=np.mean(mitad)
promedio

55.06666666666667

In [125]:
maximo=np.max(mitad)
maximo

96

In [127]:
minimo=np.min(mitad)
minimo

1

In [129]:
filas=matrix[2:,:]
filas

array([[ 6, 57, 82, 82, 41],
       [25, 38, 73, 23, 40],
       [57, 92, 41,  1, 84]])

In [131]:
suma= np.sum(filas)
suma

742

In [133]:
promedio=np.mean(filas)
promedio

49.46666666666667

In [135]:
maximo=np.max(filas)
maximo

92

In [137]:
minimo=np.min(filas)
minimo

1

In [141]:
colum=matrix[:,:]
colum

array([[25, 38, 73, 23, 40],
       [57, 92, 41,  1, 84]])